### ISSUE TITLE
问题 undefined reference to `memmem'

### ISSUE THREAD

**Issue by 1101343158code** [GCY/ESP32-CAM-MJPEG-Stream-Decoder-and-Control-Library#1]
memmem没定义怎么解决

**Comment by 1101343158code** [comment]
未定义标识符 "memmem"	TEST cam	D:\Visual stdio\ESP32-CAM\TEST cam\TEST cam\ESP32-CAM Library.cpp

**Comment by GCY** [comment]
line #199 to line #223

#ifdef _WIN10_
void* memmem(const void *buf,size_t buf_len,const void *byte_sequence,size_t byte_sequence_len)
{

   BYTE *bf = (BYTE *)buf;
   BYTE *bs = (BYTE *)byte_sequence;
   BYTE *p  = bf;

   while (byte_sequence_len <= (buf_len - (p - bf))){
      UINT b = *bs & 0xFF;
      if ((p = (BYTE *) memchr(p, b, buf_len - (p - bf))) != nullptr){
	 if ((memcmp(p, byte_sequence, byte_sequence_len)) == 0){
	    return p;
	 }
	 else{
	    p++;
	 }
      }
      else{
	 break;
      }
   }
   return nullptr;
}
#endif

**Comment by 1101343158code** [comment]
我是WIN10的，这个头文件里面有了的，但是memmem编辑的时候还是没有被标识，方便加个微信吗 18878542196，或者我加你也行

**Comment by 1101343158code** [comment]
有ESP32_CAM你这个项目方面的视频推荐下呗

**Comment by 1101343158code** [comment]
有ESP32_CAM你这个项目方面的视频推荐下呗,方便加个微信吗 18878542196，或者我加你也行
